using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using AmanatakBLL;
using AmanatakBLL.Models;

namespace Amanatak.Areas.Admin.Controllers
{
    //Generated by My Own Template
     public class IdentificationTypesController : Controller
    {
        private AmanatakContext db = new AmanatakContext();

        // GET: /Admin/IdentificationTypes/
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {

 if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;





var identificationtype = db.IdentificationType.OrderBy(e=>e.Name).Select(e=>e);


            if (!String.IsNullOrEmpty(searchString))
            {
    
                identificationtype = identificationtype.Where(c => c.Name.Contains(searchString));
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            

            return View(identificationtype.ToPagedList(pageNumber, pageSize));

        }

        // GET: /Admin/IdentificationTypes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IdentificationType identificationType = db.IdentificationType.Find(id);
            if (identificationType == null)
            {
                return HttpNotFound();
            }
            return View(identificationType);
        }

        // GET: /Admin/IdentificationTypes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Admin/IdentificationTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( IdentificationType identificationType)
        {
            if (ModelState.IsValid)
            {
                db.IdentificationType.Add(identificationType);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(identificationType);
        }

        // GET: /Admin/IdentificationTypes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IdentificationType identificationType = db.IdentificationType.Find(id);
            if (identificationType == null)
            {
                return HttpNotFound();
            }
            return View(identificationType);
        }

        // POST: /Admin/IdentificationTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( IdentificationType identificationType)
        {
            if (ModelState.IsValid)
            {
                db.Entry(identificationType).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(identificationType);
        }

        // GET: /Admin/IdentificationTypes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IdentificationType identificationType = db.IdentificationType.Find(id);
            if (identificationType == null)
            {
                return HttpNotFound();
            }
            return View(identificationType);
        }

        // POST: /Admin/IdentificationTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IdentificationType identificationType = db.IdentificationType.Find(id);
            db.IdentificationType.Remove(identificationType);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
