using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList.Mvc;
using PagedList;
using AmanatakBLL;
using AmanatakBLL.Models;

namespace Amanatak.Areas.Admin.Controllers
{
    //Generated by My Own Template
	
    public class TestClassesController : Controller
    {
        private AmanatakContext db = new AmanatakContext();

        // GET: /Admin/TestClasses/
        public ActionResult Index(string currentFilter, string searchString, int? page)
        {

 if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;





var testclass = db.TestClass.OrderBy(e=>e.Name).Select(e=>e);


            if (!String.IsNullOrEmpty(searchString))
            {
    
                testclass = testclass.Where(c => c.Name.Contains(searchString));
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);
            

            return View(testclass.ToPagedList(pageNumber, pageSize));

        }

        // GET: /Admin/TestClasses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TestClass testClass = db.TestClass.Find(id);
            if (testClass == null)
            {
                return HttpNotFound();
            }
            return View(testClass);
        }

        // GET: /Admin/TestClasses/Create
        public ActionResult Create()
        {
            string number = String.Format("{0:d9}", (DateTime.Now.Ticks / 10) % 1000000000);
            ViewBag.number = number;
            return View();
        }

        // POST: /Admin/TestClasses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Name,TypeId,Status")] TestClass testClass)
        {
            if (ModelState.IsValid)
            {
                db.TestClass.Add(testClass);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(testClass);
        }

        // GET: /Admin/TestClasses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TestClass testClass = db.TestClass.Find(id);
            if (testClass == null)
            {
                return HttpNotFound();
            }
            return View(testClass);
        }

        // POST: /Admin/TestClasses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Name,TypeId,Status")] TestClass testClass)
        {
            if (ModelState.IsValid)
            {
                db.Entry(testClass).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(testClass);
        }

        // GET: /Admin/TestClasses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TestClass testClass = db.TestClass.Find(id);
            if (testClass == null)
            {
                return HttpNotFound();
            }
            return View(testClass);
        }

        // POST: /Admin/TestClasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TestClass testClass = db.TestClass.Find(id);
            db.TestClass.Remove(testClass);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}
